### PR TITLE
Fixed All The Layout Anomalies and Added News Api Function.

### PR DESCRIPTION
**Pull request by plusminuschirag**
The Gui was in very very initial stage. Sorted all the functionalities and create purely OOPS based implementation of widgets and layouts. Main Layout is clean and easy to read now.

Added Size hints to fields so they can detect the change in window.

Added News-Api:
- Shows heading and a short summary with the link that can be opened in browser.
- Has Image of the context on side.
- Is Scrollable.

### CODE REVIEW

**Comment by techytushar** [comment]
Great Work!! But there is a small bug, when I type the input and press enter the app shutsdown, please fix that.

**Comment by plusminuschirag** [comment]
I will surely look into it, can you post your error log?

**Comment by techytushar** [comment]
So here is the error logs, when I press enter after typing into the text box I get the following error:

serror

Also while starting the application sometimes it gives this error, this might be because my internet connection was not good or the API you are using has some request limits

Screenshot from 2019-03-19 22-01-07

IMO the news feature in the app is not very useful and it also makes the app opening time quite long. We can display news when the user asks Groot to show them the news but showing it beforehand is not very useful. What do you think @omi10859

**Review by techytushar — APPROVED** [review]
LGTM, Great work :tada: , btw I see some commented code, you should remove it if its not being used anywhere.

**Comment by omi10859** [comment]
if you have changed GUI you should add screenshots

**Comment by plusminuschirag** [comment]
Screenshot from 2019-03-22 10-32-35

Here it is.

**Comment by omi10859** [comment]
When I run python base.py it takes time to open may be because you are fetching all the news from API and it does takes time. (Improve)
          [Changes] 1)Groot should start with a minimul design you can add a button when clicked on the button it will open a box with a news section.

**Comment by omi10859** [comment]
newsLibrary.py should be inside `asset/modules/`

**Comment by lalitmee** [comment]
Yeah @omi10859, you are right it should open with a minimal UI so that it will look clean and simple to use for the User. :+1:

**Comment by plusminuschirag** [comment]
Working on it.

**Comment by plusminuschirag** [comment]
Hi @omi10859 Please have a look. I have seprated them. Now Groot is minimal again and News are loaded seprately. Sometimes the news part crashes it because of limited call system but that can also be new issue for Groot.

I have removed the commented code. It's clean again and the newsApi belongs to module now.
Screenshot from 2019-03-24 23-49-42

**Review by omi10859 — COMMENTED** [review]
From next time keep in mind to always write commit message that defines your changes 
ref: https://chris.beams.io/posts/git-commit/

**Comment by omi10859** [comment]
Will check and let you know.
Meanwhile, create a new issue and start working on that
Things that need to be fixed 
- News should be fetched in random and spoken by Groot
- There will be no News button (Only one button is needed that is "speak")
- push all the changes to this branch itself

**Comment by plusminuschirag** [comment]
So press the speak button and say "news -------" which can be a specific keyword or a sentence it will treat them as keywords".

Ex : "news sports", "news India".

**Comment by omi10859** [comment]
I'm getting this error 

`Traceback (most recent call last):
  File "/Users/omkaryadav/Documents/projects/testhere/GROOT/Gui.py", line 50, in createNewsLayout
    self.newsWindow = newsBox()
  File "/Users/omkaryadav/Documents/projects/testhere/GROOT/newsWindow.py", line 14, in __init__
    self.initUI()
  File "/Users/omkaryadav/Documents/projects/testhere/GROOT/newsWindow.py", line 19, in initUI
    self.lowerLayout = TabLayout()
  File "/Users/omkaryadav/Documents/projects/testhere/GROOT/newsWindow.py", line 55, in __init__
    self.myLabel = Tiles(parent="None",description = article['description'][0:100],title=article['title'],url=article['url'],urlImage=article['urlToImage'])
  File "/Users/omkaryadav/Documents/projects/testhere/GROOT/newsWindow.py", line 72, in __init__
    data = urllib.request.urlopen(urlImage).read()
  File "/Users/omkaryadav/.pyenv/versions/3.6.0/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/omkaryadav/.pyenv/versions/3.6.0/lib/python3.6/urllib/request.py", line 517, in open
    req.timeout = timeout
AttributeError: 'NoneType' object has no attribute 'timeout'
[1]    30056 abort      python base.py`

**Comment by plusminuschirag** [comment]
Screenshot from 2019-04-02 21-09-36
It's working fine in my case. Maybe the request timed out because of traffic. This is my guess

**Comment by plusminuschirag** [comment]
@omi10859  I said "news sports".

**Comment by plusminuschirag** [comment]
Any updates?

**Review by omi10859 — APPROVED** [review]

**Comment by plusminuschirag** [comment]
Issue #36 was also linked with it. Please close it too. They were on same branch

**Pull request merged**
