### PR TITLE
Requirements.txt file for linux system is tested

### PR DESCRIPTION
**Pull request by saggu10417**
Here are some changes that were made :
remove head , pkg resources, puouplay , pycairo, and gi.vext file

### CODE REVIEW

**Comment by lalitmee** [comment]
@saggu10417, I think there is no need for adding the `speeh.mp3` file.

**Comment by saggu10417** [comment]
@lalitmee Ohk i will remove it and push a commit asap .

**Comment by krtkvrm** [comment]
Hi @saggu10417 
Any update on review by @lalitmee ?

**Comment by saggu10417** [comment]
Hey, @vkartik97 Sorry for the late reply. I was out of town, I am working on it.

**Pull request closed without merging**
