### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vips28**
The following Questions are updated in the pull request-
1.What is Groot?
2.What Groot can do?
3.How to run Groot?
4.How to contribute?

### CODE REVIEW

**Review by omi10859 — CHANGES_REQUESTED** [review]
How to run Groot?
Add technical instructions about setting up virtual env for python and installing all dependencies  

How to contribute?
Add contribution guidelines

**Comment by vips28** [comment]
Requested changes are done. Kindly check @omi10859

**Review by omi10859 — CHANGES_REQUESTED** [review]
What Groot can do?
Update with the things that Groot can do.
Like:
Groot can Play your Videos on Youtube on voice command 

Also please refer to the issue while making a PR

**Comment by omi10859** [comment]
We never push Virtualenv 
also, remember what I said about referring issue while making PR?

**Comment by vips28** [comment]
Resolved #13

**Review by omi10859 — APPROVED** [review]

**Pull request merged**
